server:
  port: 8080
  servlet:
    context-path: /manjaro
spring:
  application:
    name: manjaro01
  starter:
    name: theStarterFailedBySpace
  datasource:
    name: basicdata_20200401
    url: jdbc:mysql://192.168.100.101:3306/columbus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 111
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver'
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cestc.entity  # 注意：对应实体类的路径
#logging:
#  level:
#    com.java.code.mapper: debug

apollo:
  meta: http://200.200.6.13:1121
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
debug: true
# 异步线程配置
# 配置核心线程数
async:
  executor:
      thread:
          core_pool_size: 5
           # 配置最大线程数
           max_pool_size: 5
           # 配置队列大小
           queue_capacity: 999
           # 配置线程池中的线程的名称前缀
           namePrefix: async-service-