server:
  port: 8181
  servlet:
    context-path: /manjaro
spring:
  application:
    name: manjaro
  starter:
    name: theStarterFailedBySpace
  datasource:
    name: nei-test
    url: jdbc:mysql://127.0.0.1:3306/nei-test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver'
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0 #使用第几个数据库
    host: 127.0.0.1 #redis服务器地址
    port: 6379  #端口号
    password: 123456 #redis服务器连接密码
    timeout: 10000ms  #连接超时时间（毫秒）
    lettuce:
      pool:
        ##下面的值其实是lettuce连接池的默认配置，有兴趣的可以点进源码看一下
        max-active: 16 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cestc.entity  # 注意：对应实体类的路径
#logging:
#  level:
#    com.java.code.mapper: debug

apollo:
  meta: http://200.200.6.13:1121
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
debug: true
# 异步线程配置
# 配置核心线程数
async:
  executor:
    corePoolSize: 5
    # 配置最大线程数
    maxPoolSize: 5
    # 配置队列大小
    queueCapacity: 999
    # 配置线程池中的线程的名称前缀
    namePrefix: async-service-