apollo:
    bootstrap:
        eagerLoad:
            enabled: true
        enabled: true
    meta: http://200.200.6.13:1121
async:
    executor:
        corePoolSize: 5
        maxPoolSize: 5
        namePrefix: async-service-
        queueCapacity: 999
debug: true
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    #server:
    #    port: 8082
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.cestc.entity
server:
    port: 8083
    servlet:
        context-path: /manjaro
spring:
    application:
        name: manjaro
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        initialSize: 1
        maxActive: 20
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 1
        name: nei-test
        password: 123456
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://127.0.0.1:3306/nei-test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        validationQuery: select 'x'
    redis:
        database: 0
        host: 127.0.0.1
        lettuce:
            pool:
                max-active: 16
                max-idle: 8
                max-wait: -1ms
                min-idle: 0
        port: 6379
        timeout: 10000ms
    starter:
        name: theStarterFailedBySpace
